import {existsSync, mkdirSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import type {FileWriter} from '../interfaces/code-generator.js';

export class SyncFileWriterService implements FileWriter {
  constructor(
    private readonly name: string,
    private readonly version: string,
    private readonly inputPath: string,
  ) {}

  writeFile(filePath: string, content: string): void {
    const generatedContent = [
      '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      `// Built with ${this.name}@${this.version}`,
      `// Latest edit: ${new Date().toUTCString()}`,
      `// Source file: ${this.inputPath}`,
      '/* eslint-disable */',
      '// @ts-nocheck',
      '',
      content,
    ].join('\n');

    const dirPath = dirname(filePath);

    if (!existsSync(dirPath)) {
      mkdirSync(dirPath, {recursive: true});
    }

    writeFileSync(filePath, generatedContent);
  }

  resolveOutputPath(outputDir: string, fileName = 'type.ts'): string {
    return resolve(outputDir, fileName);
  }
}
