import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { FileWriter } from '../interfaces/code-generator';

export class SyncFileWriterService implements FileWriter {
  constructor(
    private readonly name: string,
    private readonly version: string,
    private readonly inputPath: string
  ) {}

  private redactUrl(path: string): string {
    try {
      const url = new URL(path);
      if ((url.protocol === 'http:' || url.protocol === 'https:') && url.password) {
        url.password = '***';
        return url.toString();
      }
    } catch {
      // Not a URL, return as-is
    }
    return path;
  }

  writeFile(filePath: string, content: string): void {
    const generatedContent = [
      '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      `// Built with ${this.name}@${this.version}`,
      `// Latest edit: ${new Date().toUTCString()}`,
      `// Source file: ${this.redactUrl(this.inputPath)}`,
      '/* eslint-disable */',
      '// @ts-nocheck',
      '',
      content
    ].join('\n');

    const dirPath = dirname(filePath);

    if (!existsSync(dirPath)) {
      mkdirSync(dirPath, { recursive: true });
    }

    writeFileSync(filePath, generatedContent);
  }

  resolveOutputPath(outputDir: string, fileName = 'api.ts'): string {
    return resolve(outputDir, fileName);
  }
}
