name: Bug Report
description: File a bug report to help us improve
title: '🐛 [Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏

        Please search existing issues before creating a new one.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With input file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: input-file
    attributes:
      label: Input OpenAPI File
      description: Please share the OpenAPI file that causes the issue (or a minimal reproduction)
      render: yaml
    validations:
      required: false

  - type: textarea
    id: output
    attributes:
      label: Generated Output
      description: Please share the generated code that has issues
      render: typescript
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: zod-codegen Version
      description: What version of zod-codegen are you using?
      placeholder: '0.1.0'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - OS: [e.g. iOS, Windows, Linux]
        - Node.js version: [e.g. 18.0.0]
        - Package manager: [e.g. npm, yarn, pnpm]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as logs, screenshots, etc.
