// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Built with zod-codegen@1.6.3
// Latest edit: Mon, 09 Mar 2026 20:11:48 GMT
// Source file: ./samples/pokeapi-openapi.json
/* eslint-disable */
// @ts-nocheck

// Imports
import { z } from 'zod';

// Explicit type declarations
export interface NamedAPIResource {
  name: string;
  url: string;
}
export interface PokemonType {
  slot?: number;
  type?: NamedAPIResource;
}
export interface PokemonAbility {
  ability?: NamedAPIResource;
  is_hidden?: boolean;
  slot?: number;
}
export interface PokemonSprites {
  front_default?: string;
  front_shiny?: string;
  back_default?: string;
  back_shiny?: string;
}
export interface Pokemon {
  id: number;
  name: string;
  height?: number;
  weight?: number;
  base_experience?: number;
  types?: PokemonType[];
  abilities?: PokemonAbility[];
  sprites?: PokemonSprites;
}
export interface PokemonListResponse {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: NamedAPIResource[];
}

// Components schemas
export const NamedAPIResource: z.ZodType<NamedAPIResource> = z.object({
  name: z.string(),
  url: z.url()
});
export const PokemonType: z.ZodType<PokemonType> = z.object({
  slot: z.number().int().optional(),
  type: NamedAPIResource.optional()
});
export const PokemonAbility: z.ZodType<PokemonAbility> = z.object({
  ability: NamedAPIResource.optional(),
  is_hidden: z.boolean().optional(),
  slot: z.number().int().optional()
});
export const PokemonSprites: z.ZodType<PokemonSprites> = z.object({
  front_default: z.url().optional(),
  front_shiny: z.url().optional(),
  back_default: z.url().optional(),
  back_shiny: z.url().optional()
});
export const Pokemon: z.ZodType<Pokemon> = z.object({
  id: z.number().int(),
  name: z.string(),
  height: z.number().int().optional(),
  weight: z.number().int().optional(),
  base_experience: z.number().int().optional(),
  types: z.array(PokemonType).optional(),
  abilities: z.array(PokemonAbility).optional(),
  sprites: PokemonSprites.optional()
});
export const PokemonListResponse: z.ZodType<PokemonListResponse> = z.object({
  count: z.number().int(),
  next: z.url().optional(),
  previous: z.url().optional(),
  results: z.array(NamedAPIResource)
});
export const serverConfigurations = [
  {
    url: 'https://pokeapi.co/api/v2',
    description: 'Pok\u00E9API production server'
  }
];
export const defaultBaseUrl = 'https://pokeapi.co/api/v2';
export type ClientOptions = {
  baseUrl?: string;
  serverIndex?: number;
  serverVariables?: Record<string, string>;
};
function resolveServerUrl(serverIndex?: number | undefined, serverVariables?: Record<string, string> = {}): string {
  const configs = [
    {
      url: 'https://pokeapi.co/api/v2'
    }
  ];
  const idx = serverIndex ?? 0;
  if (idx < configs.length) {
    const config = configs[idx];
    let url = config.url;
    if (config.variables && serverVariables) {
      for (const [key, value] of Object.entries(serverVariables)) {
        url = url.replace(new RegExp('\\{' + key + '\\}', 'g'), value);
      }
    }
    return url;
  }
  return 'https://pokeapi.co/api/v2';
}
export class ResponseValidationError<T> extends Error {
  readonly response: Response;
  readonly error: z.ZodError<T>;
  constructor(message: string, response: Response, error: z.ZodError<T>) {
    super(message);
    this.name = 'ResponseValidationError' as const;
    this.response = response;
    this.error = error;
  }
  get data(): T {
    return this.response.json() as T;
  }
}

// Client class
export default class PokAPI {
  readonly #baseUrl: string;
  constructor(options: ClientOptions) {
    const resolvedUrl = options.baseUrl !== null ? options.baseUrl : resolveServerUrl(options.serverIndex, options.serverVariables);
    this.#baseUrl = resolvedUrl;
  }
  protected getBaseRequestOptions(): Partial<Omit<RequestInit, 'method' | 'body'>> {
    return {};
  }
  protected async handleResponse<T>(
    response: Response,
    method: string,
    path: string,
    options: _params___Record_string__string___number___boolean___data___unknown__contentType___string__headers___Record_string__string__
  ): Promise<Response> {
    return response;
  }
  protected async makeRequest<T>(
    method: string,
    path: string,
    options: _params___Record_string__string___number___boolean___data___unknown__contentType___string__headers___Record_string__string__ = {}
  ): Promise<T> {
    const baseUrl = new URL(path, this.#baseUrl);
    const url =
      options.params && Object.keys(options.params).length > 0
        ? (() => {
            Object.entries(options.params)
              .filter(([, value]) => value !== undefined)
              .forEach(([key, value]) => {
                baseUrl.searchParams.set(key, String(value));
              });
            return baseUrl.toString();
          })()
        : baseUrl.toString();
    const baseOptions = this.getBaseRequestOptions();
    const contentType = options.contentType === 'application/x-www-form-urlencoded' ? 'application/x-www-form-urlencoded' : 'application/json';
    const baseHeaders = baseOptions.headers !== undefined ? baseOptions.headers : {};
    const headers = Object.assign({}, baseHeaders, { 'Content-Type': contentType }, options.headers !== undefined ? options.headers : {});
    const body =
      options.data !== undefined
        ? options.contentType === 'application/x-www-form-urlencoded'
          ? (() => {
              const params = new URLSearchParams();
              Object.entries(options.data).forEach(([key, value]) => {
                params.set(key, String(value));
              });
              return params.toString();
            })()
          : JSON.stringify(options.data)
        : null;
    const rawResponse = await fetch(url, Object.assign({}, baseOptions, { method, headers: headers, body: body }));
    const response = await this.handleResponse<T>(rawResponse, method, path, options);
    if (!response.ok) throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    return await response.json();
  }
  /**
   * Get Pokémon by ID or name
   *
   * @param id Pokémon ID or name
   * @returns {Pokemon}
   */
  async getPokemonById(id: string): Promise<Pokemon> {
    const response = await this.makeRequest('GET', `/pokemon/${id}`, {});
    const parsedPokemon = Pokemon.safeParse(response);
    if (!parsedPokemon.success) {
      throw new ResponseValidationError<Pokemon>(`Invalid pokemon: ${parsedPokemon.error.errors.map((error) => error.message).join(', ')}`, response, parsedPokemon.error);
    }
    return parsedPokemon.data;
  }
  /**
   * Get list of Pokémon
   *
   * @param limit
   * @param offset
   * @returns {PokemonListResponse}
   */
  async getPokemonList(limit?: number, offset?: number): Promise<PokemonListResponse> {
    const response = await this.makeRequest('GET', '/pokemon', { params: { limit: limit, offset: offset } });
    const parsedPokemonListResponse = PokemonListResponse.safeParse(response);
    if (!parsedPokemonListResponse.success) {
      throw new ResponseValidationError<PokemonListResponse>(
        `Invalid pokemonListResponse: ${parsedPokemonListResponse.error.errors.map((error) => error.message).join(', ')}`,
        response,
        parsedPokemonListResponse.error
      );
    }
    return parsedPokemonListResponse.data;
  }
}
